### ISSUE TITLE
Fix incidental `from_numpy` unit test failure

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#484]
https://github.com/computationalgeography/lue/actions/runs/3058322905/jobs/4934401817#step:8:331

**Comment by kordejong** [comment]
```
ERROR: test_dtype (from_numpy_test.FromNumPyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$SRC_DIR/source/framework/python/test/lue_test/test_case.py", line 21, in wrapper
    test_case(self)
  File "$SRC_DIR/source/framework/python/test/from_numpy_test.py", line 127, in test_dtype
    lue_array = lfr.from_numpy(numpy_array, partition_shape, 9.9)
RuntimeError: Rank of array shape and partition shape must be equal (1 != 2)

----------------------------------------------------------------------
```

**Comment by kordejong** [comment]
```
Traceback (most recent call last):                                                                                                              
  File "/home/kor/miniconda3/envs/lue/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction                         
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)                                                                                     
RuntimeError: Object of type <class 'numpy.ndarray'> appears to be C subclassed NumPy array, void scalar, or allocated in a non-standard way.NumPy reserves the right to change the size of these structures. Projects are required to take this into account by either recompiling against a specific NumPy version or padding the struct and enforcing a maximum NumPy version.
```

**Comment by kordejong** [comment]
Can't reproduce, won't fix. It may already be fixed.

**Comment by kordejong** [comment]
Well, the unit tests just return before testing anything. Re-opened. See `framework/python/test/from_numpy_test.py`.

**Comment by kordejong** [comment]
```
pybind11::handle::dec_ref() is being called while the GIL is either not held or invalid. Please see https://pybind11.readthedocs.io/en/stable/advanced/misc.html#common-sources-of-global-interpreter-lock-errors for debugging advice.
If you are convinced there is no bug in your code, you can #define PYBIND11_NO_ASSERT_GIL_HELD_INCREF_DECREFto disable this check. In that case you have to ensure this #define is consistently used for all translation units linked into a given pybind11 extension, otherwise there will be ODR violations.The failing pybind11::handle::dec_ref() call was triggered on a numpy.ndarray object.
terminate called after throwing an instance of 'std::runtime_error'
  what():  pybind11::handle::dec_ref() PyGILState_Check() failure.
```
