### ISSUE TITLE
Fix failing Python unit tests in Windows / Conda package workflow

### ISSUE THREAD

**Issue by kordejong** [computationalgeography/lue#493]
#490 introduced code that results in:

```
ImportError: Failed to import test module: from_numpy_test
Traceback (most recent call last):
  File "%PREFIX%\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "%PREFIX%\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "%SRC_DIR%\source\framework\python\test\from_numpy_test.py", line 1, in <module>
    import lue.framework as lfr
  File "C:\Users\runneradmin\AppData\Local\Temp\build\lib\python3.9\lue\lue\__init__.py", line 24, in <module>
    from .lue_py import *
ImportError: DLL load failed while importing lue_py: The specified module could not be found.
```

Rebuild on a Windows machine and figure out which dll is missing. Running tests in other workflows works fine.

**Comment by kordejong** [comment]
May have to do with the docopt dll being install in lib instead of bin. Reported this to the docopt Conda package maintainer.
https://github.com/conda-forge/docopt.cpp-feedstock/issues/4

**Comment by kordejong** [comment]
Already fixed some time ago.
